//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEFEntities : DbContext
    {
        public BDEFEntities()
            : base("name=BDEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ProductosConReclamos> ProductosConReclamos { get; set; }
        public virtual DbSet<ProductosMejorCalificados> ProductosMejorCalificados { get; set; }
        public virtual DbSet<CantidadDePedidosPorCliente> CantidadDePedidosPorCliente { get; set; }
        public virtual DbSet<ProductosMasVendidos> ProductosMasVendidos { get; set; }
        public virtual DbSet<CantidadDeReclamosPorAgente> CantidadDeReclamosPorAgente { get; set; }
        public virtual DbSet<Agente> Agente { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<Producto_por_Pedido> Producto_por_Pedido { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Reclamo> Reclamo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
